#175756592 Created a welcome Page for Visit Africa App
Soma-Technologies-Inc/visitAfrica-frontend pull request #2
Opened 2020-11-18 11:21 UTC by Floride125-art

#### What does this PR do?
It indicates a welcome page task that I have worked on.
#### Description of Task to be completed?
The welcome Page task that I worked on is the first page a user see when open the visit Africa app. This page simply summarize what the visit Africa app do and allow user to continue to the next page where she or he can be able to register and create an account with  us. 
#### How should this be manually tested?
clone it  
run flutter pub get to install dependencies  
run flutter run to start
#### Any background context you want to provide?
As the user you should click on continue button to be able to proceed on the next pages of Visit Africa App.
#### What are the relevant pivotal tracker stories?
#175756592
#### Screenshots (if appropriate)
![FirstP](https://user-images.githubusercontent.com/71024941/99524302-eb0dfa00-29a0-11eb-9d76-2c4bda44745f.jpg)

#### Questions:
N/A

2020-11-19 07:47 UTC, dianahub250 commented
Great work! You can proceed!

2020-11-19 08:04 UTC, Sandrine21 approved these changes
The work is well done. I am good with it.

2020-11-19 08:44 UTC, VedaDom requested changes

2020-11-19 08:44 UTC, VedaDom commented on lib/welcomePage.dart
> +              "assets/cover.png",
Can you put images in the images folder? `assets/images/example.png`

2020-11-19 08:44 UTC, VedaDom commented on lib/signup.dart
> +        backgroundColor: Color(0xffB15C1E),
Why do we have this `app bar ` here not in the original design? It kills everything. what do you think about removing it?

2020-11-19 08:44 UTC, VedaDom commented on lib/welcomePage.dart
> +                'Welcome',
Aren't we supposed to have Welcome to **visit Africa** ? what changed your mind?

2020-11-19 08:44 UTC, VedaDom commented on lib/welcomePage.dart
> +              padding: const EdgeInsets.only(top: 630.0, left: 30.0),
Can you find another way to move this to bottom?

2020-11-23 14:53 UTC, Rita-12397 approved these changes

2020-11-24 09:37 UTC, dianahub250 approved these changes
This is the Good work!

2020-11-25 10:25 UTC, mujohn26 reviewed
LGTM

2020-11-25 12:30 UTC, VedaDom approved these changes

2020-11-25 13:22 UTC, merged