#175756608 Created a Home Page
Soma-Technologies-Inc/visitAfrica-frontend pull request #3
Opened 2020-11-23 09:55 UTC by dianahub250

#### What does this PR do?
Creating a home page for Visit Africa App
#### Description of Task to be completed?
- The user can be able to view most visited places
-The use must be able to search 
-The user can be able to navigate to side menu
#### How should this be manually tested?
-Clone it
-Run flutter pub get to install dependencies
-Run it by using flutter run command
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#https://www.pivotaltracker.com/story/show/175756608
#### Screenshots (if appropriate)
![Screenshot_1606125218](https://user-images.githubusercontent.com/71551337/99948814-593e1e00-2d0d-11eb-8b78-b4990eb19044.png)

#### Questions:
N/A

2020-11-23 14:04 UTC, Rita-12397 approved these changes

2020-11-24 08:43 UTC, Sandrine21 approved these changes
Good, you can conyinue.

2020-11-25 10:17 UTC, mujohn26 requested changes

2020-11-25 10:17 UTC, mujohn26 commented on lib/main.dart
> +    title: 'Todos ',
What's the meaning of this tittle ?

2020-11-25 10:17 UTC, mujohn26 commented on test/widget_test.dart
> +// // This is a basic Flutter widget test.
What is the use of this file ? I see it's a commented line.

2020-12-02 11:04 UTC, mujohn26 approved these changes
Good

2020-12-03 10:07 UTC, merged