#175494111 creating sign up
Soma-Technologies-Inc/visitAfrica-frontend pull request #4
Opened 2020-11-23 10:05 UTC by Sandrine21

#### What does this PR do?
sign up page.

#### Description of Task to be completed?

the user will be able to sign up using email or social media.

#### How should this be manually tested?

first, clone it.
then run flutter pub get to install dependencies.
after run flutter run to run it.

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?

https://www.pivotaltracker.com/story/show/175494111

#### Screenshots (if appropriate)

![Screenshot_20201123-120029](https://user-images.githubusercontent.com/72881099/99949686-1cf9d480-2d84-11eb-9d61-d0e1be40d172.png)

#### Questions:
N/A

2020-11-23 14:02 UTC, Rita-12397 approved these changes

2020-11-23 16:30 UTC, Jajabenit250 requested changes
this Pull Request is empty it has no change

2020-11-24 08:18 UTC, mujohn26 reviewed
Hey @Sandrine21 This PR doesn't have any changes, actually what did you worked on ?

2020-11-24 09:35 UTC, dianahub250 approved these changes
Well done Sandrine you can continue

2020-11-26 09:08 UTC, mujohn26 approved these changes
Looks good to me.

2020-11-26 09:08 UTC, mujohn26 commented on lib/model/signup.model.dart
> +  String confirmp;
Please provide a descriptive  variable name.

2020-11-26 10:49 UTC, merged