#175494145 Created a bookNow form
Soma-Technologies-Inc/visitAfrica-frontend pull request #8
Opened 2020-12-01 14:09 UTC by Floride125-art

#### What does this PR do?
This PR indicates a BookNow page that I have designed.
#### Description of Task to be completed?
This book now page is a form that allow users to book accommodations, transport, or halls depending on the which places visitors wants to visit.
#### How should this be manually tested?
-Clone it
-Run flutter pub get to install dependencies
-Run it by using flutter run command in any text editor you wants
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#https://www.pivotaltracker.com/n/projects/2474529/stories/175494145
#### Screenshots (if appropriate)
![bookNow](https://user-images.githubusercontent.com/71024941/100750792-34be0200-33ef-11eb-945e-6e0ad28e86e3.jpg)

#### Questions:
N/A

2020-12-04 14:35 UTC, VedaDom requested changes

2020-12-04 14:35 UTC, VedaDom commented on lib/views/Bookhall.view.dart
> +  List<Mybookdata> mybookinfo = [];
Can you try to change the way you name your class and variable names?

2020-12-04 14:35 UTC, VedaDom commented on lib/views/Bookhall.view.dart
> +                      hall.clear();
I this necessary?

2020-12-04 14:35 UTC, VedaDom commented on lib/views/bookhotel.view.dart
> +  List<Mybookdata> mybookdata = [];
These names should be self-explanatory.

2020-12-04 14:35 UTC, VedaDom commented on lib/views/bookhotel.view.dart
> +                      timeTo.clear();
Is that necessary?

2020-12-07 08:04 UTC, Floride125-art commented on lib/views/bookhotel.view.dart
> +                      timeTo.clear();
yes because I need to clear the information entered by the user on previous form

2020-12-09 11:32 UTC, mujohn26 approved these changes
Good!

2020-12-09 11:32 UTC, merged